language: python
before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O conda.sh
        - bash conda.sh -b -p ~/miniconda
        - ~/miniconda/bin/conda config --system --add channels conda-forge
install:
        - ~/miniconda/bin/conda install --yes conda-build conda-verify
script:
        - ~/miniconda/bin/conda build .
