{% set data = load_setup_py_data() %}

package:
    name: dusql
    version: {{ data['version'] }}

source:
    path: ./

requirements:
    build:
        - {{ compiler('c') }}
        - sqlite
    host:
        - python >=3.5
        - pip
    run:
        - python
        - sqlalchemy
        - pandas
        - tqdm

build:
    noarch: python
    script: 
        - "${CC} ${CFLAGS} -fPIC -shared src/dusql/closure.c -o src/dusql/closure.so"
        - "{{ PYTHON }} -m pip install . -vv"

test:
    files:
        - test
        - setup.cfg
    requires:
        - pytest
        - pytest-cov
    commands:
        - py.test --cov-report=xml:{{ environ.get('PWD','') }}/coverage.xml
        - dusql --help

about:
    home: {{ data['url'] }}
    summary: {{ data['description'] }}
    license: APACHE
    license_file: LICENSE


