version: 2
jobs:
    build:
        docker:
            - image: continuumio/miniconda3
            - image: circleci/postgres
        steps:
            - checkout
            - run: conda install conda-build conda-verify postgresql
            - run: psql -h localhost -U postgres -d circle_test -f sql/dusql_schema.sql
            - run: conda build .
