version: 2
jobs:
    build:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout
            - run: conda install conda-build
            - run: conda build .
